# Air
[air]
app_name = "goproxy-china"
debug_mode = true
address = "localhost:8080"
minifier_enabled = true
gzip_enabled = true

# Zerolog
[zerolog]
logger_level = "debug"

# Goproxy
[goproxy]
go_bin_name = "go"
kodo_endpoint = "<KODO_ENDPOINT>"
kodo_access_key = "<KODO_ACCESS_KEY>"
kodo_secret_key = "<KODO_SECRET_KEY>"
kodo_bucket_name = "<KODO_BUCKET_NAME>"
