# Air
[air]
app_name = "goproxy-china"
debug_mode = true
address = "localhost:8080"
minifier_enabled = true
gzip_enabled = true
coffer_enabled = true
i18n_enabled = true

# Zerolog
[zerolog]
logger_level = "debug"

# Qiniu Cloud
[qiniu]
access_key = "<ACCESS_KEY>"
secret_key = "<SECRET_KEY>"
kodo_endpoint = "<KODO_ENDPOINT>"
kodo_bucket_name = "<KODO_BUCKET_NAME>"
kodo_bucket_endpoint = "<KODO_BUCKET_ENDPOINT>"

# Goproxy
[goproxy]
go_bin_name = "go"
max_go_bin_workers = 8
timeout = "60s"
auto_redirect = false
local_cache_root = "/tmp"
